# Generated by Django 4.2 on 2023-04-26 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0007_alter_profile_address_alter_profile_org'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='Название')),
                ('topic', models.CharField(choices=[('cd', 'Заключение договора'), ('cs', 'Изменение параметра услуг'), ('ud', 'Корректировка договора'), ('dd', 'Расторжение договора')], max_length=3, verbose_name='Тема')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('closed_on', models.DateField(blank=True, default='', verbose_name='Срок обработки')),
                ('channel', models.CharField(choices=[('e', 'Email'), ('p', 'Телефон'), ('m', 'Мессенджер')], max_length=3, verbose_name='Канал поступления')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.profile')),
                ('contract', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
