# Generated by Django 4.2 on 2023-04-26 07:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appeal', '0002_alter_appeal_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='closed_on',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Срок обработки'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
