# Generated by Django 4.2 on 2023-04-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0004_alter_appeal_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('r', 'Обработано'), ('n', 'Не обработано')], default='r', max_length=3, verbose_name='Статус'),
        ),
    ]
