# Generated by Django 4.2 on 2023-04-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_org_web_site'),
        ('appeal', '0005_appeal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='client',
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('r', 'Обработано'), ('n', 'Не обработано')], default='n', max_length=3, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='client',
            field=models.ManyToManyField(to='agents.profile'),
        ),
    ]
