# Generated by Django 4.2 on 2023-04-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_org_web_site'),
        ('appeal', '0006_remove_appeal_client_alter_appeal_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='client',
        ),
        migrations.AddField(
            model_name='appeal',
            name='client',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='agents.profile'),
            preserve_default=False,
        ),
    ]
