# Generated by Django 4.2 on 2023-04-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0007_remove_appeal_client_appeal_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='topic',
            field=models.CharField(choices=[(None, 'Your String For Display'), ('cd', 'Заключение договора'), ('cs', 'Изменение параметра услуг'), ('ud', 'Корректировка договора'), ('dd', 'Расторжение договора')], max_length=3, verbose_name='Тема'),
        ),
    ]
