# Generated by Django 4.2 on 2023-04-28 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_org_web_site'),
        ('appeal', '0008_alter_appeal_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='channel',
            field=models.CharField(choices=[(None, ''), ('e', 'Email'), ('p', 'Телефон'), ('m', 'Мессенджер')], max_length=3, verbose_name='Канал поступления'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='agents.profile'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[(None, ''), ('r', 'Обработано'), ('n', 'Не обработано')], default='n', max_length=3, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='topic',
            field=models.CharField(choices=[(None, ''), ('cd', 'Заключение договора'), ('cs', 'Изменение параметра услуг'), ('ud', 'Корректировка договора'), ('dd', 'Расторжение договора')], max_length=3, verbose_name='Тема'),
        ),
    ]
