# Generated by Django 4.2 on 2023-04-30 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_alter_profile_address_alter_profile_org'),
        ('contracts', '0007_alter_contract_file_alter_contract_name'),
        ('appeal', '0009_alter_appeal_channel_alter_appeal_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appeal', to='agents.profile'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.contract'),
        ),
    ]
