# Generated by Django 4.2 on 2023-05-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0010_alter_appeal_client_alter_appeal_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('r', 'Обработано'), ('n', 'Не обработано')], default='n', max_length=3, verbose_name='Статус'),
        ),
    ]
