# Generated by Django 4.2 on 2023-04-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_appeal_application_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('s', 'Согласовано'), ('n', 'Не согласовано')], default='n', max_length=3, verbose_name='Статус'),
        ),
    ]
