# Generated by Django 4.2 on 2023-04-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('applications', '0003_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.service'),
        ),
    ]
