# Generated by Django 4.2 on 2023-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_name'),
        ('applications', '0005_remove_application_services_application_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='services',
        ),
        migrations.AddField(
            model_name='application',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.service'),
        ),
    ]
