# Generated by Django 4.2 on 2023-04-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0007_remove_appeal_client_appeal_client'),
        ('applications', '0006_remove_application_services_application_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='appeal',
            field=models.ForeignKey(blank=True, default='', on_delete=models.SET(''), to='appeal.appeal'),
        ),
    ]
