# Generated by Django 4.2 on 2023-04-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_name'),
        ('applications', '0008_alter_application_appeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='services',
            field=models.ManyToManyField(to='services.service'),
        ),
    ]
