# Generated by Django 4.2 on 2023-04-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_application_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_on']},
        ),
    ]
