# Generated by Django 4.2 on 2023-04-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0007_remove_appeal_client_appeal_client'),
        ('applications', '0011_alter_application_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='appeal',
            field=models.ForeignKey(default=1, on_delete=models.SET(''), to='appeal.appeal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='priority',
            field=models.CharField(choices=[('l', 'Низкий'), ('m', 'Средний'), ('h', 'Высокий')], default='l', max_length=3, verbose_name='Приоритет'),
        ),
    ]
