# Generated by Django 4.2 on 2023-04-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_alter_application_appeal_alter_application_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='services',
        ),
    ]
