# Generated by Django 4.2 on 2023-04-30 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0010_alter_appeal_client_alter_appeal_contract'),
        ('applications', '0013_remove_application_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appeal.appeal'),
        ),
    ]
