# Generated by Django 4.2 on 2023-04-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_application_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='send_on',
            field=models.DateField(blank=True, null=True, verbose_name='Отправлено клиенту'),
        ),
    ]
