# Generated by Django 4.2 on 2023-04-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_application_send_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('n', 'Не согласовано'), ('s', 'Согласовано')], default='n', max_length=3, verbose_name='Статус'),
        ),
    ]
