# Generated by Django 4.2 on 2023-05-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('n', 'Не согласована'), ('s', 'Согласована'), ('k', 'У клиента'), ('c', 'Закрыта')], default='n', max_length=3, verbose_name='Статус'),
        ),
    ]
