# Generated by Django 4.2 on 2023-05-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0011_alter_appeal_status'),
        ('applications', '0017_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app', to='appeal.appeal'),
        ),
    ]
