# Generated by Django 4.2 on 2023-04-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_remove_profile_has_marketing_access_profile_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес'},
        ),
        migrations.AlterModelOptions(
            name='org',
            options={'verbose_name': 'Организация'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Представитель организации'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Строение'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=64, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=64, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=64, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='org',
            name='web_site',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Web-сайт'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_sales_access',
            field=models.BooleanField(default=False, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='priority',
            field=models.CharField(blank=True, choices=[('l', 'Низкий'), ('m', 'Средний'), ('h', 'Высокий')], default='', max_length=3, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=128, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
    ]
