# Generated by Django 4.2 on 2023-04-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_address_options_alter_org_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), related_name='user_org', to='agents.org'),
        ),
    ]
