# Generated by Django 4.2 on 2023-04-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_org_web_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='adress_users', to='agents.address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='user_org', to='agents.org'),
        ),
    ]
