# Generated by Django 4.2 on 2023-04-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_created_on_contract_creted_by_contract_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='creted_by',
            new_name='created_by',
        ),
    ]
