# Generated by Django 4.2 on 2023-04-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_rename_creted_by_contract_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='uploads/', verbose_name='Договор'),
        ),
    ]
