# Generated by Django 4.2 on 2023-04-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='contracts_files/', verbose_name='Договор'),
        ),
    ]
