# Generated by Django 4.2 on 2023-04-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(upload_to='contracts/', verbose_name='Договор'),
        ),
    ]
