# Generated by Django 4.2 on 2023-04-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_alter_contract_file_alter_contract_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
    ]
