# Generated by Django 4.2 on 2023-04-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_alter_contract_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='send_on',
            field=models.DateField(blank=True, null=True, verbose_name='Отправлено клиенту'),
        ),
    ]
