# Generated by Django 4.2 on 2023-05-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_alter_profile_address_alter_profile_org'),
        ('contracts', '0011_remove_contract_send_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='agents.profile'),
        ),
    ]
