# Generated by Django 4.2 on 2023-04-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Название'),
        ),
    ]
