# Generated by Django 4.2 on 2023-04-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
