# Generated by Django 4.2 on 2023-04-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуги'},
        ),
    ]
