# Generated by Django 4.2 on 2023-05-01 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0010_alter_contract_send_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('send_on', models.DateField(blank=True, null=True, verbose_name='Отправлено клиенту')),
                ('status', models.CharField(choices=[('a', 'Активно'), ('s', 'Приостановлено'), ('c', 'Закрыто')], default='a', max_length=3, verbose_name='Статус')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.contract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
