# Generated by Django 4.2 on 2023-05-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_contract_name_alter_contract_profile'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='contracts.contract'),
        ),
    ]
